#!/bin/bash
set -euo
echo "[Agent] start."

if [[ -z $MG_ENV ]]; then
  echo "[Agent] ERROR: Need \$MG_ENV configuration."
  exit 1
fi


atf="/ss3/buildkite_agent_token"
if [[ ! -f $atf ]]; then # Not a buildkite agent; just running an op.
  echo "[Agent] no agent token"
  exit 0
fi

if [[ ! -d /root/.ssh ]]; then mkdir /root/.ssh; fi
if [[ ! -f /root/ssh/id_rsa ]]; then #
  echo "[Agent] no agent id rsa"
  exit 0
fi
cp /root/ssh/id_rsa /root/.ssh/id_rsa
chmod 400 /root/.ssh/id_rsa

at=$(cat $atf)
echo "[Agent] Configuring as BuildKite Agent"

#if [[ ! -d /etc/buildkite-agent/ ]]; then mkdir /etc/buildkite-agent/; fi
#cat /tmp/buildkite-agent.cfg >> /etc/buildkite-agent/buildkite-agent.cfg
sed -i "s/xxx/$at/g" /etc/buildkite-agent/buildkite-agent.cfg
