#!/bin/bash
set -euo
echo "[Smith] start."

cd /smith

UNITY_LIC_ULF="${UNITY_LIC_ULF:-}"

mkdir -p /root/.cache/unity3d
mkdir -p /root/.local/share/unity3d/Unity/

if [[ ! -z "$UNITY_LIC_ULF" ]]; then
  echo "$UNITY_LIC_ULF" > /root/.local/share/unity3d/Unity/Unity_lic.ulf
elif [[ -f /ss3/unity.ulf ]]; then
  echo "Copying license from SS3"
  cat /ss3/unity.ulf | tr -d '\r' > /root/.local/share/unity3d/Unity/Unity_lic.ulf
fi

if [[ ! -f /root/.local/share/unity3d/Unity/Unity_lic.ulf ]]; then
  echo "No licence file!"
  exit 1
fi

mkdir -p work
mkdir -p cache

# echo "Smith awaiting lazy-start by agent."
# tail -f /dev/null
cd work
lf="ci.log"
rm -rf "$lf"
rm -rf "smith.lock" # In case the prior version did not shut down.
rm -rf "smith.cmd" # In case the prior version did not shut down.
echo "[Smith] Running as $(whoami) in $(pwd) [$lf]"
xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' /opt/Unity/Editor/Unity \
  -nographics \
  -batchmode \
  -quit \
  -projectPath ./ \
  -logFile "$lf" \
  -androidSdkRoot /root/Android \
  -JdkPath /usr/lib/jvm/java-8-oracle \
  -executeMethod Agent.Smith.CI &
