#!/bin/bash
set -euo
if [[ -z "$SMITH_TARGET" ]]; then
  echo "[Smith] no target; not starting Unity."
  exit 0
fi

echo "[Smith] start."

cd /smith

UNITY_LIC_ULF="${UNITY_LIC_ULF:-}"

mkdir -p /root/.cache/unity3d
mkdir -p /root/.local/share/unity3d/Unity/

if [[ ! -z "$UNITY_LIC_ULF" ]]; then
  echo "$UNITY_LIC_ULF" > /root/.local/share/unity3d/Unity/Unity_lic.ulf
elif [[ -f /ss3/unity.ulf ]]; then
  echo "[Smith] Copying license from SS3"
  cat /ss3/unity.ulf | tr -d '\r' > /root/.local/share/unity3d/Unity/Unity_lic.ulf
fi

if [[ ! -f /root/.local/share/unity3d/Unity/Unity_lic.ulf ]]; then
  echo "[Smith] No licence file!"
  exit 1
fi

#mkdir -p work
#mkdir -p cache

/bin/smith.sh
