#!/bin/bash
set -euo pipefail

echo "BUILDKITE command: ${BUILDKITE_COMMAND:-}"
echo "BUILDKITE path: ${BUILDKITE_BUILD_CHECKOUT_PATH:-}"

/bin/smith.sh

running=$(ps -ef | grep "/opt/Unity/Editor/Unity" | grep -v "grep")
echo "[Smith] Running? ${running}"
