#!/bin/bash
set -euo
echo "[Smith] start."

UNITY_LIC_ULF="${UNITY_LIC_ULF:-}"

local_dir=".local"
lic_file="${local_dir}/share/unity3d/Unity/Unity_lic.ulf"
mkdir -p ".cache/unity3d"
mkdir -p "${local_dir}/share/unity3d/Unity/"

if [[ ! -z "$UNITY_LIC_ULF" ]]; then
  echo "$UNITY_LIC_ULF" > "${lic_file}"
elif [[ -f /ss3/unity.ulf ]]; then
  echo "[Smith] Copying license from SS3"
  cat /ss3/unity.ulf | tr -d '\r' > "${lic_file}"
fi

if [[ ! -f "${lic_file}" ]]; then
  echo "[Smith] No licence file!"
  exit 1
fi

echo "[Smith] cleaning working directory."

#mkdir -p work
#mkdir -p cache
